In [ ]:
!pip install google-api-python-client pandas requests pillow pytesseract isodate
!apt-get install -y tesseract-ocr



Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.


In [ ]:
import json
import os
import requests
import pandas as pd
from googleapiclient.discovery import build
from PIL import Image
import pytesseract
import isodate


In [ ]:
# Sumedh's yt api key
# API_KEY = "AIzaSyB4VVAteFZVKx4gti7eODWTddHckFBoxD4"

# Aditya's yt api key
# API_KEY = "AIzaSyCfdWrE07A8Hy-e9MXOmcLsW98LcaZp_B8"

# Harshal's Api keys
API_KEY = "AIzaSyDwDvb0qVWCPPTv8sRVOojA4FvOA9-6Zfg"

youtube = build("youtube", "v3", developerKey=API_KEY)


In [ ]:
os.makedirs("data/raw", exist_ok=True)
os.makedirs("data/thumbnails", exist_ok=True)


In [ ]:
# with open("category.json", "r") as f:
#     CATEGORY_QUERIES = json.load(f)

# CATEGORY_QUERIES.keys()
with open("categoryStartFrom_News.json", "r") as f:
    CATEGORY_QUERIES = json.load(f)

CATEGORY_QUERIES.keys()



dict_keys(['News_Current_Affairs_Clickbait_Queries'])

In [ ]:
def search_videos(query, max_results=10):
    req = youtube.search().list(
        part="snippet",
        q=query,
        type="video",
        regionCode="IN",
        maxResults=max_results
    )
    return req.execute()["items"]


In [ ]:
def get_video_details(video_ids):
    req = youtube.videos().list(
        part="snippet,contentDetails,statistics",
        id=",".join(video_ids)
    )
    return req.execute()["items"]


In [ ]:
def download_thumbnail(url, video_id):
    path = f"data/thumbnails/{video_id}.jpg"
    if not os.path.exists(path):
        img = requests.get(url).content
        with open(path, "wb") as f:
            f.write(img)
    return path


In [ ]:
records = []

for category, queries in CATEGORY_QUERIES.items():
    print("Collecting:", category)

    for q in queries:
        search_results = search_videos(q)

        video_ids = [v["id"]["videoId"] for v in search_results]
        if not video_ids:
            continue

        videos = get_video_details(video_ids)

        for v in videos:
            snippet = v["snippet"]
            stats = v.get("statistics", {})

            duration = isodate.parse_duration(
                v["contentDetails"]["duration"]
            ).total_seconds() / 60

            thumb_url = snippet["thumbnails"]["high"]["url"]
            thumb_path = download_thumbnail(thumb_url, v["id"])

            records.append({
                "category": category,
                "video_id": v["id"],
                "title": snippet["title"],
                "description": snippet.get("description", ""),
                "duration_min": round(duration, 2),
                "views": int(stats.get("viewCount", 0)),
                "likes": int(stats.get("likeCount", 0)),
                "thumbnail_path": thumb_path,
                "label": "",          # YOU will fill
                "verified": 0         # set to 1 after checking
            })


Collecting: News_Current_Affairs_Clickbait_Queries


In [ ]:
len(records)


405

In [ ]:
df = pd.DataFrame(records)
df.head()


category     video_id  \
0  News_Current_Affairs_Clickbait_Queries  L2G6KnKzwng   
1  News_Current_Affairs_Clickbait_Queries  7bLNLDSeB-c   
2  News_Current_Affairs_Clickbait_Queries  PEJQNRklhKk   
3  News_Current_Affairs_Clickbait_Queries  kLzL8U5uflc   
4  News_Current_Affairs_Clickbait_Queries  MF6ybNDnVYU   

                                               title  \
0  US Breaking News LIVE: American  Troops Storm ...   
1  BREAKING NEWS! Winnie Odinga Shocking News aft...   
2                             (속보) 윤석열 대통령, 충격 근황...   
3  BREAKING NEWS! Ida Odinga Shocking Truth about...   
4  Elon Musk Makes Shocking Future Predictions At...   

                                         description  duration_min   views  \
0  US Breaking News LIVE: American  Troops Storm ...          0.00    7878   
1                      #breakingnews #ruto #gachagua          9.58    9685   
2  #속보 #국민의힘 #뉴스 #뉴스속보 #윤석열 #윤석열대통령 #이슈 #이재명 #정치 ...          0.40  141542   
3          #breakingnews #ruto #gachagua#railaodinga          8.98    3023   
4  At a World Economic Forum discussion with Blac...          7.32  964800   

   likes                   thumbnail_path label  verified  
0     33  data/thumbnails/L2G6KnKzwng.jpg               0  
1      0  data/thumbnails/7bLNLDSeB-c.jpg               0  
2  15511  data/thumbnails/PEJQNRklhKk.jpg               0  
3      0  data/thumbnails/kLzL8U5uflc.jpg               0  
4  14278  data/thumbnails/MF6ybNDnVYU.jpg               0

In [ ]:
df.drop_duplicates(subset="video_id", inplace=True)

df.to_csv("raw_ytData_Starts_From_News.csv", index=False)

# below  one contains videos(data) from  Movies_Bollywood,TV_Serials_Clickbait_Queries,Finance_Money_Scams_Clickbait_Queries
# df.to_csv("raw_youtube_partial.csv", index=False)

print("Saved rows:", len(df))
# backup FIle
# df.to_csv("raw_clickbait_candidates.csv", index=False)



Saved rows: 376


In [ ]:
df["category"].value_counts()


category
News_Current_Affairs_Clickbait_Queries    376
Name: count, dtype: int64

In [ ]:
News_df= df[df["category"] == "Religion_Spirituality_Clickbait_Queries	"]
News_df.head()


Empty DataFrame
Columns: [category, video_id, title, description, duration_min, views, likes, thumbnail_path, label, verified]
Index: []

In [ ]:
News_df[[
    "title",
    "duration_min",
    "views",
    "likes"
]].head(15)


Empty DataFrame
Columns: [title, duration_min, views, likes]
Index: []

In [ ]:
ocr_texts = []

for path in df["thumbnail_path"]:
    try:
        img = Image.open(path)
        text = pytesseract.image_to_string(img)
        ocr_texts.append(text.strip())
    except:
        ocr_texts.append("")


In [ ]:
df["thumbnail_text"] = ocr_texts
df.to_csv("raw_ytData_Starts_From_News_ocr.csv", index=False)


In [ ]:
len(df)
ocr_df = df["thumbnail_text"]
ocr_df.head(50)

0              GREENLAND INVADED?\nae WILDEST MOVE YET?
1                                          et LS &\n\nA
2                                                      
3                                                      
4                                                      
5                              HAAG Ss zeal\nFl Al\na |
6                              ee RMN\nSHOCKS THE WORLD
7                      CEE ee TL SETS R nin\nSUL E 0 EL
8                                                      
9                                                      
10     Tem D PAZ w AL\noles acu ar\n\n    \n \n\nCA cre
11                                                     
12            Le or AE\nQUA\n\nIMMIGRANT CRIMINALS NOT]
13                                                     
14                                     x\n\nCe a\n4s on
15                                   ALES\n\n   \n\nCoe
16                                                     
17           Tite: Prieta L4\nCAUGHT ON BODYCAM| a\n\n=
18              The Impact of News\nm Media On Informed
19                              ETT\n\nmi\n\nMoe) PA'S)
20    EUSA ALL p08 tala a\n\nBios Spr Abate)\nLpetod...
21                                                     
22                                                     
23                                                     
24                                                     
25                                          SHEANAUPONT
26                                                     
27                                                     
28                                                     
29                                                     
30                                                  HSI
31                                     ee\niy PCT\nay "
32                                                     
33    ST Xe\n\nee cer\ncoment\nilar Reenter nerd\nra...
34                                                     
35                                                     
36                                                     
37                                                     
38                                                     
39                       VV N |\nLom Sf\nPART 2 CONFIRM
40                                 TET ink ony\nComrie)
41    _10 WARSHIPS, SECRET ORDERS:\nTRUMP'S IRAN PLA...
42                                      Senona\lExposed
43                                                     
44                     CELEBS Eareele2) Lb 1 =|) | sien
45                              AT PBA x CoHfeet HSS Ct
46                                                     
47                                                     
48                                                     
49                                                     
Name: thumbnail_text, dtype: object

In [ ]:
import shutil
shutil.rmtree("/content/data/thumbnails")


In [ ]:
# Model Training starts Here -
import pandas as pd

df = pd.read_csv("MASTER_DATASET.csv")

print("Shape:", df.shape)
df.head()


Shape: (3813, 14)


category     video_id  \
0  Movies_Bollywood_Clickbait_Queries  TmrloFLnaio   
1  Movies_Bollywood_Clickbait_Queries  8zN2uU388QU   
2  Movies_Bollywood_Clickbait_Queries  7gqCU86EDiA   
3  Movies_Bollywood_Clickbait_Queries  Plrg0XP6gZg   
4  Movies_Bollywood_Clickbait_Queries  xTndy2AhuaY   

                                               title  \
0  English Vinglish (HD) | Sridevi, Adil Hussain,...   
1  BHIKHARI Vikrama Movie | Hrithik Roshan | Teja...   
2  Bareilly Ki Barfi (2017) Full Hindi Movie (4K)...   
3  Naam Shabana 2017 Action Full Movie 4K | Aksha...   
4  Shubh Mangal Saavdhan | Ayushmann Khurrana & B...   

                                         description  duration_min     views  \
0  -Subscribe To Watch Best Hindi Full Movies:  h...        128.33  10104767   
1  BHIKHARI Vikrama Movie | Hrithik Roshan | Teja...        127.70  12641682   
2  Bareilly Ki Barfi (2017) is a romantic comedy,...        118.13  10708879   
3  Naam Shabana 2017 Action Hindi Full Movie 4K |...        147.85   5335033   
4  🔔 Tap the bell icon so you never miss an updat...        100.10   1354344   

    likes                   thumbnail_path  label  verified thumbnail_text  \
0  107331  data/thumbnails/TmrloFLnaio.jpg      0         1            NaN   
1   29642  data/thumbnails/8zN2uU388QU.jpg      1         1     thet ttale   
2  100804  data/thumbnails/7gqCU86EDiA.jpg      0         1            NaN   
3   38268  data/thumbnails/Plrg0XP6gZg.jpg      0         1            NaN   
4    8628  data/thumbnails/xTndy2AhuaY.jpg      0         1            NaN   

                                              reason thumbnail_text_cleaned  \
0  Legitimate content with proper description, ca...                    NaN   
1  Borderline case - insufficient evidence of leg...             thet ttale   
2  Legitimate content with proper description, ca...                    NaN   
3  Legitimate content with proper description, ca...                    NaN   
4  Legitimate content with proper description, ca...                    NaN   

   thumbnail_text_valid  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0

In [ ]:
df = df[df["verified"] == 1].copy()
print("Verified rows:", df.shape)



Verified rows: (3813, 14)


In [ ]:
df["label"] = df["label"].astype(int)

text_cols = [
    "title",
    "description",
    "thumbnail_text_cleaned"
]

for col in text_cols:
    df[col] = df[col].fillna("")

num_cols = [
    "duration_min",
    "views",
    "likes",
    "thumbnail_text_valid"
]

for col in num_cols:
    df[col] = df[col].fillna(0)


In [ ]:
df["text"] = (
    df["title"] + " " +
    df["description"] + " " +
    df["thumbnail_text_cleaned"]
)


In [ ]:
from sklearn.preprocessing import OneHotEncoder

cat_encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
X_cat = cat_encoder.fit_transform(df[["category"]])


In [ ]:
import numpy as np

df["title_length"] = df["title"].str.len()

df["caps_ratio"] = df["title"].apply(
    lambda x: sum(1 for c in x if c.isupper()) / max(len(x), 1)
)

df["likes_view_ratio"] = df["likes"] / (df["views"] + 1)

# NEW FEATURES (ADD HERE)

# 1. Description length (non-clickbait tends to be longer & explanatory)
df["desc_length"] = df["description"].str.len()

# 2. Question marks in title (clickbait uses more)
df["question_count"] = df["title"].str.count(r"\?")

# 3. Exclamation marks in title (clickbait emphasis)
df["exclam_count"] = df["title"].str.count(r"!")
X_num = df[
    [
        "duration_min",
        "views",
        "likes",
        "likes_view_ratio",
        "title_length",
        "caps_ratio",
        "thumbnail_text_valid",
        "desc_length",
        "question_count",
        "exclam_count"
    ]
].values




In [ ]:
df[
    ["desc_length", "question_count", "exclam_count"]
].describe()


desc_length  question_count  exclam_count
count  3813.000000     3813.000000   3813.000000
mean    839.340677        0.128245      0.185943
std    1050.113315        0.376475      0.492112
min       0.000000        0.000000      0.000000
25%      45.000000        0.000000      0.000000
50%     454.000000        0.000000      0.000000
75%    1218.000000        0.000000      0.000000
max    5000.000000        4.000000      9.000000

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=4000,
    stop_words="english",
    ngram_range=(1, 2)
)

X_text = tfidf.fit_transform(df["text"])


In [ ]:
from scipy.sparse import hstack

X = hstack([
    X_text,
    X_num,
    X_cat
])

y = df["label"].values


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1500,
    class_weight="balanced"
)

model.fit(X_train, y_train)


LogisticRegression(class_weight='balanced', max_iter=1500)

In [ ]:
#Logistic Regression

from sklearn.metrics import classification_report, confusion_matrix

y_prob = model.predict_proba(X_test)[:, 1]
y_pred = (y_prob > 0.6).astype(int)


print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[388  27]
 [194 154]]
              precision    recall  f1-score   support

           0       0.67      0.93      0.78       415
           1       0.85      0.44      0.58       348

    accuracy                           0.71       763
   macro avg       0.76      0.69      0.68       763
weighted avg       0.75      0.71      0.69       763



In [ ]:
#Linear SVM
#Discarded
from sklearn.svm import LinearSVC

svm = LinearSVC(class_weight="balanced", max_iter=3000)
svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print("SVM Results")
print(confusion_matrix(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))


SVM Results
[[246 169]
 [ 93 255]]
              precision    recall  f1-score   support

           0       0.73      0.59      0.65       415
           1       0.60      0.73      0.66       348

    accuracy                           0.66       763
   macro avg       0.66      0.66      0.66       763
weighted avg       0.67      0.66      0.66       763



/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [ ]:
#Naive Bayes
#Discarded
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix, classification_report

train_idx, test_idx = train_test_split(
    df.index,
    test_size=0.2,
    random_state=42,
    stratify=df["label"]
)
X_text_train = X_text[train_idx]
X_text_test = X_text[test_idx]

y_train = df.loc[train_idx, "label"].values
y_test = df.loc[test_idx, "label"].values

nb = MultinomialNB()
nb.fit(X_text_train, y_train)

y_pred_nb = nb.predict(X_text_test)

print(confusion_matrix(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

[[343  72]
 [143 205]]
              precision    recall  f1-score   support

           0       0.71      0.83      0.76       415
           1       0.74      0.59      0.66       348

    accuracy                           0.72       763
   macro avg       0.72      0.71      0.71       763
weighted avg       0.72      0.72      0.71       763



In [ ]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

X_num_only = df[
    [
        "duration_min",
        "views",
        "likes",
        "likes_view_ratio",
        "title_length",
        "caps_ratio",
        "thumbnail_text_valid",
        "desc_length",
        "question_count",
        "exclam_count"
    ]
].values

Xn_train, Xn_test, y_train, y_test = train_test_split(
    X_num_only, y, test_size=0.2, random_state=42, stratify=y
)

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

rf.fit(Xn_train, y_train)

y_pred_rf = rf.predict(Xn_test)

print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))


[[407   8]
 [ 96 252]]
              precision    recall  f1-score   support

           0       0.81      0.98      0.89       415
           1       0.97      0.72      0.83       348

    accuracy                           0.86       763
   macro avg       0.89      0.85      0.86       763
weighted avg       0.88      0.86      0.86       763

